### ISSUE TITLE
Design home page

### ISSUE THREAD

**Issue by K-jais** [sifa123/Dev-Kitchen#1]
I can design the home page of this restaurant project using tech stacks like HTML, CSS, JS, and BOOTSTRAP. I have previously made a home page for the restaurant project using animations and CSS styles.

**Comment by sifa123** [comment]
awesome!!! I have already made a diagram. I will share you with this and hope after that you can start your designing on the home page.

**Comment by K-jais** [comment]
That's great. A diagram will be a great thing for designing the home page.

**Comment by sifa123** [comment]
You can start working and please join our channel, you will find the link in random channel.

**Comment by K-jais** [comment]
Ok ma'am

**Comment by aditya687** [comment]
I want to design the homepage with css animations and html. Please assign me this issue @sifa123

**Comment by K-jais** [comment]
I have already made 80% of the home page and will make the PR in 2 days.

**Comment by sifa123** [comment]
> I want to design the homepage with css animations and html. Please assign me this issue @sifa123

Hey @aditya687 would you like to work on other issue? Please check this #62
