### ISSUE TITLE
Would like to add login page !

### ISSUE THREAD

**Issue by siddhi-244** [sifa123/Dev-Kitchen#14]
Assign this to me under devincept

**Comment by harshita9621** [comment]
Can I work on this issue under DevIncept21

**Comment by siddhi-244** [comment]
> Can I work on this issue under DevIncept21

I asked it first

**Comment by sifa123** [comment]
Thanks, @siddhi-244 and @harshita9621, for raising the issue. I would assign someone who raises this first, then if she/he is stuck anywhere, other contributors can help him/her. The main thing is we won't add login page, if I want to add something, I will raise an issue for your contribution.
