### ISSUE TITLE
Image Slider below navbar

### ISSUE THREAD

**Issue by neha030** [sifa123/Dev-Kitchen#22]
I would like to add the image slider below the navbar which will contain different pictures
Please assign me this issue under DCP'21

**Comment by harshita9621** [comment]
Can I work on this issue

**Comment by sifa123** [comment]
@neha030 you can work on this, try to make it attractive.

**Comment by aditya687** [comment]
I can make a image slider to scroll the images from left to right. Please assign me this issue @sifa12.
