### ISSUE TITLE
Add map, icon, changing the side of mail on navbar

### ISSUE THREAD

**Issue by sifa123** [sifa123/Dev-Kitchen#23]
You have to add Map/Location(if user clicks on this text it will take you on google map) on the first navbar in left side and email, phone number should be in right side(if user click on email it should take her on Gmail so that she can compose email, send it, and same for mobile, can make call from desktop to mobile).
I have marked on black navbar work on this

![Screenshot (162)](https://user-images.githubusercontent.com/63462931/125188880-4ace5380-e257-11eb-9a6d-f0c537a8e20f.png)
![Screenshot (163)](https://user-images.githubusercontent.com/63462931/125188882-4c981700-e257-11eb-8888-7ccf2c0c0348.png)

**Comment by RakeshCharpe** [comment]
I would like to work on this issue under DCP'21 . Please assign to me

**Comment by sifa123** [comment]
> I would like to work on this issue under DCP'21 . Please assign to me

Sure
