### ISSUE TITLE
Update the Readme file

### ISSUE THREAD

**Issue by vanishasamriddhi** [sifa123/Dev-Kitchen#24]
In the Readme file I can see some fatal errors that is deteriorating the repo. Do assign me under DevIncept.

**Comment by swathi-469** [comment]
I would like to work on this issue please assign me

**Comment by sifa123** [comment]
> In the Readme file I can see some fatal errors that is deteriorating the repo. Do assign me under DevIncept.

Could you describe more what errors you found?

**Comment by vanishasamriddhi** [comment]
Some grammatical errors and also we can describe a bit more about the website in the read me file. That would add more values.

**Comment by sifa123** [comment]
> Some grammatical errors and also we can describe a bit more about the website in the read me file. That would add more values.

Okay
