### ISSUE TITLE
Issue and PR Template 

### ISSUE THREAD

**Issue by DarshGupta1910** [sifa123/Dev-Kitchen#28]
Hey project admins can I work on this issue?

Thanks, 
Darsh Gupta

**Comment by sifa123** [comment]
What do you want to add? Can you please explain?

**Comment by DarshGupta1910** [comment]
so when someone opens up an issue or pulls a request for Dev-Kitchen they will be notified with a template they should follow. 
You can check <a href = "https://github.com/samccone/issue-and-pr-templates">this</a>

**Comment by sifa123** [comment]
@DarshGupta1910 you can work on this.
