### ISSUE TITLE
Add Contributors Section in readme

### ISSUE THREAD

**Issue by payaldutta** [sifa123/Dev-Kitchen#31]
I want to add a contributors section in the readme to showcase all the valuable contributors of this repository.
@aakankshabhende  Do assign me this issue under DCP'21.
Thank You.

**Comment by sifa123** [comment]
@payaldutta you can add this section.

**Comment by ashish-patwal** [comment]
hey @sifa123 , if this issue is open can i work on this ?

**Comment by sifa123** [comment]
> hey @sifa123 , if this issue is open can i work on this ?

sure, you can

**Comment by ashish-patwal** [comment]
Thanks ! I will start working on it .
