### ISSUE TITLE
Footer of the website

### ISSUE THREAD

**Issue by harshita0802goswami** [sifa123/Dev-Kitchen#4]
the footer will contain Social links and feedback form

**Comment by shindesuyog** [comment]
I would like to work on footer. please assign this to me @sifa123

**Comment by sifa123** [comment]
Hi @harshita0802goswami, @shindesuyog, Thanks for raising the issue. I will assign all of you to this project, but we have to wait for some days, you know our program will start within a few days.

**Comment by shindesuyog** [comment]
okay, no problem

**Comment by sifa123** [comment]
You can start working on footer

**Comment by harshita0802goswami** [comment]
Hi @sifa123 can you pls provide your details like social media links to add on footer

**Comment by sifa123** [comment]
You can add our DevIncept's link- website, linkedin, facebook. You can check this link https://devincept.tech/

**Comment by harshita0802goswami** [comment]
Is this issue closed? I haven't made any PR yet

**Comment by sifa123** [comment]
Yes, @harshita0802goswami. I have closed this issue because Shinde made a PR for that. I should have assigned it earlier, unfortunately, I forgot that. Also, we have to add another footer, I already mentioned you in an issue, please check it.
