### ISSUE TITLE
Make README.md informative

### ISSUE THREAD

**Issue by maitridshah** [sifa123/Dev-Kitchen#41]
I want to add 

- sneak peek into the website section
- program admin section
- how to get started section
- contributors section

**Comment by maitridshah** [comment]
Please assign me this under DCP'21

**Comment by sifa123** [comment]
Hey, @maitridshah, I have assigned someone for the contributors section, you can add other sections.

**Comment by maitridshah** [comment]
Okay no problem  I will work on other sections and add something more. Please assign me this under DCP'21

**Comment by maitridshah** [comment]
Can you assign me this?

**Comment by sifa123** [comment]
> Can you assign me this?

Okay
