### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by anupamishra333** [sifa123/Dev-Kitchen#43]
Can we add Scroll to top button ? if yes then can u please assign to me

**Comment by sifa123** [comment]
yes @anupamishra333 , we can add that.

**Comment by anupamishra333** [comment]
Added a Pull Request see Screen Shot here and Check Working.
![button](https://user-images.githubusercontent.com/66557767/126778612-5ee5a843-b88d-475c-9888-8c4f5687e1e8.png)
