### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by ri-tae-ka** [sifa123/Dev-Kitchen#44]
I would like to add a responsive navbar and add functionality to it by linking all pages to the navbar.

Please assign me this issue.

**Comment by sifa123** [comment]
Thanks @ri-tae-ka , you can work on this.

**Comment by ri-tae-ka** [comment]
Thanks for assigning me this issue.
Can you assign it under Devincept 2021.

**Comment by priyanshi5** [comment]
@sifa123 I would like to work on this issue. Please assign this issue to me under DCP21.

**Comment by ri-tae-ka** [comment]
closes #46
