### ISSUE TITLE
Menu page

### ISSUE THREAD

**Issue by Tulsi25** [sifa123/Dev-Kitchen#6]
Website can include a menu page which which can link to some other pages like : 
i) Beverages
ii) Indian Snacks - this can include some chaat and indian snacks
iii) Chinese corner - includes chinese dishes.
iv) North Indian / south Indian food.
v) Starters food 
vi) Veggies , Rotis and Rice.
vii) Salad
viii) Thali's and many more.

**Comment by sifa123** [comment]
Superb @Tulsi25 ...I can assign you to design the menu page, but please wait until the program starts.

**Comment by Tulsi25** [comment]
sure mam

**Comment by sifa123** [comment]
You can start working on the menu page.

**Comment by Tulsi25** [comment]
Ok mam

**Comment by aditya687** [comment]
Ma'am can I work on this issue? I can add the food items with their starters in the menu page @sifa123
