### ISSUE TITLE
Fav-Icon

### ISSUE THREAD

**Issue by vanishasamriddhi** [sifa123/Dev-Kitchen#8]
I would like to add the fav-icon on the website.
and I'm from DevIncept

**Comment by SarveshLimaye** [comment]
hey i am a contributor from devincept and would like to add fav-icon. Please assign me the following issue.

**Comment by sifa123** [comment]
You can add fav-icon now

**Comment by vanishasamriddhi** [comment]
You need to assign this issue to me.
