### ISSUE TITLE
There is no Code in Repo

### ISSUE THREAD

**Issue by heet-kumar** [sifa123/Dev-Kitchen#9]
We need to start this project from the scratch or this project files are hidden . Else provide link of the website so that how much work is done in the website till now I want to see it .

If you want to start from the scratch then I have one suggestion if you like for Website design for this project if you want to see .

**Comment by heet-kumar** [comment]
@sifa123 reply to the above query

**Comment by sifa123** [comment]
No, I haven't uploaded any projects file, but I will add those as soon as possible. 
I have already made a diagram. I will share with you.

**Comment by heet-kumar** [comment]
sure
